version: '3'

services:
  # Creación del contenedor para el Servidor
  web:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
  # Creación del contenedor para PHP
  php:
    container_name: php-container
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  # Creación del contenedor para Mysql
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: dbinicial
        MYSQL_USER: test
        MYSQL_PASSWORD: test
    ports:
        - "3306:3306"
